### PR TITLE
Add --client-id flag

### PR DESCRIPTION
**Pull request by natebosch**

### CODE REVIEW

**Comment by natebosch** [comment]
cc @devoncarew

Would you prefer this is specific to the plugin used (other options are `vim-lsp` and `coc.nvim`, those won't show up unless users make a change like this themselves), or should it be general to the editor?

Should we consider making this flag required?

**Comment by devoncarew** [comment]
> Would you prefer this is specific to the plugin used (other options are `vim-lsp` and `coc.nvim`, those won't show up unless users make a change like this themselves), or should it be general to the editor?

What we've done w/ other plugins is to use the general client as the name, and if there's a subset of workflows / client types we can about, to them suffix the name with that. So `VS-Code` for the VS Code dart plugin, and `VS-Code-Remote` when VS Code is used in the remote workflow (a pretty different way of using VS Code, and useful for us to know that a segment of users is using it that way).

Just capturing a `vim` client will be the biggest benefit here. After that, it might be useful to know which vim client is the most used? If they're all equally used? That data would be useful, but less important than just knowing how many overall vim users there are.

**Review by devoncarew — APPROVED** [review]
👍

**Comment by natebosch** [comment]
SGTM. I'll add `--client-version` sometime soon. Unfortunately any clients who aren't using this plugin won't pick this up and will continue to not report the client. Even the clients using this plugin won't pick it up right away, I don't know the typical update cadence for most users and we can't force an update.

Other places to look at:

I updated the wiki here:
https://github.com/neoclide/coc.nvim/wiki/Language-servers#dart - this relies on users setting up the command manually.

You might want to file an issue or a PR to add it here:
https://github.com/iamcco/coc-flutter/blob/50c73ef2a8905aee15b1cdcfb03401204bc92ae8/src/server/lsp/index.ts#L48

and here:
https://github.com/mattn/vim-lsp-settings/blob/df8da2aace8286b5d66cdc638d16901b2677c1b8/installer/install-analysis-server-dart-snapshot.sh#L26

**Comment by devoncarew** [comment]
Ah, I didn't realize we the vim space was so fragmented. It looks like they're using the LSP implementation.

Thanks for the change!

**Comment by natebosch** [comment]
yeah there are even more options than that, but I _think_ they cover a good chunk of usage.

YCM is another:
https://github.com/ycm-core/lsp-examples/blame/22447090f185731f92a6b5f52f4d356f4788f836/README.md#L63

The vim ecosystem and configuration for LSP is quite ad-hoc. I suspect we're going to have a very long tail of clients that don't report an ID unless we make the flag a requirement to run. A less disruptive option might be to use `window/showMessage` to nag if it wasn't passed.

**Pull request merged**
